# Generated by Django 3.2.3 on 2022-02-10 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscrape', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedProducts',
        ),
    ]
