# Generated by Django 3.2.3 on 2022-03-13 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscrape', '0004_trendsearch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trendsearch',
            old_name='linK',
            new_name='link',
        ),
    ]
